version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - dev.env
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    env_file:
      - dev.env

volumes:
  data: {}
